# Site settings
title: HackMilton
email: jacob_aronoff16@milton.edu
url: https://github.com/milton-programming/
description: "HackMilton is a new hackathon that will run November 15th. "
contactDescription: "If you are interested in attending contact us at the following email: "
introText: "On November 15th, Milton Academy will hold their first ever hackathon."
info: "Check back in the coming week for more information"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/milton-programming/

# Build settings
markdown: kramdown
permalink: pretty
